name: Deploy React App to GitHub Pages

on:
  # Triggers the workflow on push events to the main branch
  push:
    branches: [ "master" ]
  # Allows you to run the workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages      # Branch where the built files will go
          folder: dist         # Folder with the final build output
          
